"""
Call Warden 性能测试脚本（T-1783441015097-cdfe）

按从小到大的顺序测试 4 个真实仓库的 refresh-all 与核心查询性能：
1. admin       (257K 行 Java)
2. android     (898K 行 Java/Kotlin)
3. ios_muzoplayer (1.58M 行 ObjC/C)
4. firmware    (34M 行 C)  ← 千万级挑战

使用 Python API 直接调用（绕过 cw.py subprocess 的 Python 3.14 + Windows
WAL 间歇性失败问题）。

每个仓库测量：
- refresh-all 耗时（秒）
- DB 文件大小（MB）
- 符号总数 / 文件数 / 调用数
- 核心查询性能：
  - search（模糊搜索）
  - get_callers（谁调用）
  - get_callees（调用谁）
  - get_topological_order（拓扑排序）
  - detect_clones（克隆检测）

使用方式：
    python tests/_perf_test.py --repo admin
    python tests/_perf_test.py --repo android
    python tests/_perf_test.py --repo ios_muzoplayer
    python tests/_perf_test.py --repo firmware
    python tests/_perf_test.py --all   # 依次测试全部

注意：本脚本不推送任何代码到远端，不修改仓库代码。
DB 文件存储在 $HOME/.callwarden/<hash>/callwarden.db。
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

# 确保能导入 callwarden 包
_PKG_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PKG_ROOT not in sys.path:
    sys.path.insert(0, _PKG_ROOT)

from callwarden.db.db import CodeGraphDB
from callwarden.config import get_project_db_path

# 仓库配置：名称 -> (根路径, 描述, .callwardenignore 规则)
REPOS = {
    "admin": {
        "root": r"C:\git_work\callwarden\testcode\admin",
        "desc": "云端 admin（Java Maven 多模块，257K 行）",
        "ignore_rules": [],  # admin 规模小，无需排除
    },
    "android": {
        "root": r"C:\git_work\callwarden\testcode\android",
        "desc": "Android app（Java + Kotlin，898K 行）",
        "ignore_rules": [
            "build/",
            "*/build/",
            ".gradle/",
            "*/.gradle/",
        ],
    },
    "ios_muzoplayer": {
        "root": r"C:\git_work\callwarden\testcode\ios_muzoplayer",
        "desc": "iOS app（ObjC + Swift + C，1.58M 行）",
        "ignore_rules": [
            "Pods/",
            "*/Pods/",
            "Carthage/",
            "*/Carthage/",
            "build/",
            "*/build/",
            # 第三方依赖（xcframework 路径超 Windows MAX_PATH，且非业务代码）
            "third/",
            "*/third/",
            # frameworks（预编译二进制头文件，路径深）
            "*.xcframework/",
            "*/xcframework/",
        ],
    },
    "firmware": {
        "root": r"C:\git_work\callwarden\testcode\firmware",
        "desc": "固件主仓库（C/C++，34M 行，2.71GB）",
        "ignore_rules": [
            # 第三方应用源码（体积大，非业务代码）
            "applications/application/boa/",
            "applications/application/squeezelite/",
            "applications/application/esp/",
            "applications/application/apple_remote/",
            "applications/application/audio_cast/",
            "applications/application/intercom/",
            "applications/application/aws_iot/",
            "applications/application/wiim_lvgl_app/",  # LVGL 第三方 GUI 库（18500 文件中占大量）
            "applications/application/cxdish_src_v1.0.0.6/",  # 第三方源码包
            # 中间件中的第三方库
            "middleware/private/mplayer/",
            "middleware/private/shairport/",
            "middleware/private/libbsa/",
            "middleware/private/mfi_airplay/",
            # 预编译二进制和镜像
            "device/legacy/",
            "system/misc/melody/",
            "system/misc/mp3/",
            "system/misc/res_aispeech/",
            "system/misc/res_sensory/",
            "system/misc/res_tx/",
            "system/misc/rftest/",
            "system/misc/test/",
            "system/misc/tx_tone/",
            "system/tool/",
            # 构建脚本和工具
            "build/",
            "back_images/",
        ],
    },
}


def get_db_size_mb(db_path: str) -> float:
    """获取 DB 文件大小（MB），不存在返回 0。"""
    try:
        return os.path.getsize(db_path) / (1024 * 1024)
    except OSError:
        return 0.0


def write_ignore_file(repo_root: str, rules: list[str]) -> None:
    """在仓库根目录写入 .callwardenignore 文件。"""
    if not rules:
        return
    ignore_path = os.path.join(repo_root, ".callwardenignore")
    content = "# Auto-generated by _perf_test.py for performance testing\n"
    content += "# Excludes third-party libraries and build artifacts\n\n"
    for rule in rules:
        content += f"{rule}\n"
    with open(ignore_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


# P13: perf 回归基线 —— 防止 _write_calls_db() 等热循环 SQL 回潮
# 基线文件存储各仓库的阶段耗时，每次测试时对比，超过 1.5x 打印警告
PERF_BASELINE_PATH = os.path.join(_PKG_ROOT, "tests", "_perf_baseline.json")

# 允许的回归倍数（超过此倍数则警告）
REGRESSION_THRESHOLD = 1.5


def _load_perf_baseline() -> dict:
    """加载 perf 基线 JSON。"""
    try:
        import json
        with open(PERF_BASELINE_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _print_stage_baseline_comparison(repo_name: str, timings: dict):
    """打印阶段耗时与基线的对比。

    如果某阶段耗时超过基线的 REGRESSION_THRESHOLD 倍，打印红色警告。
    这能帮助快速发现性能回归（如 _write_calls_db 热循环 SQL 回潮）。
    """
    baseline = _load_perf_baseline()
    repo_baseline = baseline.get(repo_name, {}).get("stage_timings", {})
    if not repo_baseline:
        print(f"  (无基线对比，运行 --update-baseline 创建基线)")
        return

    print(f"\n  ── 基线对比 ──")
    has_regression = False
    for stage, current_val in timings.items():
        if stage in ("files_total", "files_parsed", "files_unchanged"):
            continue
        baseline_val = repo_baseline.get(stage)
        if baseline_val is None or baseline_val <= 0:
            continue
        ratio = current_val / baseline_val
        status = "✓" if ratio <= REGRESSION_THRESHOLD else "✗ 回归!"
        color = "" if ratio <= REGRESSION_THRESHOLD else "  ← WARNING"
        print(f"    {stage:25s}: {current_val:6.2f}s vs {baseline_val:6.2f}s  ({ratio:.2f}x) {status}{color}")
        if ratio > REGRESSION_THRESHOLD:
            has_regression = True

    if has_regression:
        print(f"\n  ⚠ 检测到性能回归！请检查上述标记的阶段。")
        print(f"    常见原因：热循环 SQL 回潮（如 _write_calls_db 逐条 INSERT）、")
        print(f"    FTS 触发器未禁用、_from_db 未跳过重写等。")


def _update_perf_baseline(results: list):
    """用本次测试结果更新基线文件。"""
    import json
    baseline = _load_perf_baseline()
    for result in results:
        repo = result.get("repo")
        refresh = result.get("refresh", {})
        stage_timings = refresh.get("stage_timings")
        if repo and stage_timings:
            baseline[repo] = {
                "stage_timings": stage_timings,
                "elapsed_sec": refresh.get("elapsed_sec", 0),
                "updated_at": __import__("time").strftime("%Y-%m-%d %H:%M:%S"),
            }
    with open(PERF_BASELINE_PATH, "w", encoding="utf-8") as f:
        json.dump(baseline, f, indent=2, ensure_ascii=False)
    print(f"\n✓ 基线已更新: {PERF_BASELINE_PATH}")


def open_db(repo_root: str, repo_name: str) -> CodeGraphDB:
    """打开指定仓库的 CodeGraphDB。

    使用项目目录内的 DB 路径（tests/_perf_db/<repo>/callwarden.db），
    绕过 TRAE Sandbox 对 ~/.callwarden 目录 -shm 文件的访问限制。

    Args:
        repo_root: 仓库根目录
        repo_name: 仓库名称（用于构造 DB 子目录）
    """
    # DB 放在 tests/_perf_db/<repo_name>/ 下，确保沙箱可写
    perf_db_dir = os.path.join(_PKG_ROOT, "tests", "_perf_db", repo_name)
    os.makedirs(perf_db_dir, exist_ok=True)
    db_path = os.path.join(perf_db_dir, "callwarden.db")
    # 如果存在旧的 DB，先删除（确保干净测试）
    for suffix in ["", "-wal", "-shm"]:
        old = db_path + suffix
        if os.path.exists(old):
            try:
                os.remove(old)
            except OSError:
                pass
    db = CodeGraphDB(db_path=db_path, workspace_root=repo_root)
    return db


def ensure_workspace(db: CodeGraphDB, name: str, root: str) -> int | None:
    """确保 workspace 已注册并激活，返回 workspace_id。"""
    # 检查是否已注册
    existing = None
    for ws in db.list_workspaces():
        if ws["root_path"] == root or ws["name"] == name:
            existing = ws
            break

    if existing:
        ws_id = existing["id"]
        if not existing.get("is_active"):
            db.set_active_workspace(ws_id)
        return ws_id
    else:
        ws_id = db.register_workspace(name, root)
        db.set_active_workspace(ws_id)
        return ws_id


def timed(fn, *args, **kwargs):
    """执行函数并计时，返回 (result, elapsed_sec)。"""
    start = time.time()
    result = fn(*args, **kwargs)
    elapsed = time.time() - start
    return result, elapsed


def test_repo(repo_name: str, skip_refresh: bool = False, skip_clone: bool = True) -> dict:
    """测试单个仓库的性能。

    Args:
        repo_name: 仓库名称（admin/android/ios_muzoplayer/firmware）
        skip_refresh: 跳过 refresh-all（用于已刷新的仓库）
        skip_clone: 跳过 clone detect（默认跳过，不污染 refresh 性能报告）

    Returns:
        性能测试结果 dict
    """
    cfg = REPOS[repo_name]
    repo_root = cfg["root"]
    # DB 放在 tests/_perf_db/<repo_name>/ 下，绕过沙箱对 ~/.callwarden 的限制
    perf_db_dir = os.path.join(_PKG_ROOT, "tests", "_perf_db", repo_name)
    db_path = os.path.join(perf_db_dir, "callwarden.db")
    result = {
        "repo": repo_name,
        "desc": cfg["desc"],
        "root": repo_root,
        "db_path": db_path,
        "steps": [],
    }

    print(f"\n{'='*60}")
    print(f"测试仓库: {repo_name} — {cfg['desc']}")
    print(f"路径: {repo_root}")
    print(f"DB: {db_path}")
    print(f"{'='*60}")

    # 1. 写入 .callwardenignore
    if cfg["ignore_rules"]:
        print(f"\n[1/6] 写入 .callwardenignore ({len(cfg['ignore_rules'])} 条规则)...")
        write_ignore_file(repo_root, cfg["ignore_rules"])
        result["steps"].append({"step": "write_ignore", "rules_count": len(cfg["ignore_rules"])})
    else:
        print(f"\n[1/6] 无需 .callwardenignore（规模小）")

    # 2. 打开 DB + 注册/激活 workspace
    print(f"[2/6] 打开 DB + 注册 workspace...")
    db_size_before = get_db_size_mb(db_path)
    print(f"  DB 初始大小: {db_size_before:.2f} MB")

    db = open_db(repo_root, repo_name)
    ws_id, reg_elapsed = timed(ensure_workspace, db, repo_name, repo_root)
    print(f"  workspace_id={ws_id} ({reg_elapsed:.2f}s)")
    result["workspace_id"] = ws_id

    # 3. refresh-all（核心性能指标）
    if not skip_refresh:
        print(f"[3/6] refresh-all（构建代码图谱）...")
        # 确保忽略规则被加载：CodeGraphDB 在构造时已读取 .callwardenignore
        # build_full_graph 会自动扫描文件
        try:
            _, elapsed = timed(db.build_full_graph, force=False)
            db_size_after = get_db_size_mb(db_path)
            print(f"  refresh-all 完成: {elapsed:.1f}s ({elapsed/60:.1f}min)")
            print(f"  DB 最终大小: {db_size_after:.2f} MB (增量 {db_size_after - db_size_before:+.2f} MB)")
            result["refresh"] = {
                "elapsed_sec": elapsed,
                "elapsed_min": elapsed / 60,
                "db_size_before_mb": db_size_before,
                "db_size_after_mb": db_size_after,
                "db_delta_mb": db_size_after - db_size_before,
            }
            # P13: 捕获阶段耗时，用于回归基线对比
            stage_timings = getattr(db, "_stage_timings", None)
            if stage_timings:
                result["refresh"]["stage_timings"] = stage_timings
                # 打印阶段耗时对比基线
                _print_stage_baseline_comparison(repo_name, stage_timings)
        except Exception as e:
            print(f"  refresh-all 失败: {e}")
            result["refresh"] = {"elapsed_sec": 0, "error": str(e)[:500]}
    else:
        print(f"[3/6] 跳过 refresh-all（使用已有数据）")

    # 4. 统计信息
    print(f"[4/6] 获取统计信息...")
    try:
        stats, elapsed = timed(db.get_stats)
        symbols = stats.get("total_symbols", 0)
        files = stats.get("total_files", 0)
        calls = stats.get("total_calls", 0)
        print(f"  stats ({elapsed:.3f}s): 符号={symbols}, 文件={files}, 调用={calls}")
        result["stats"] = {
            "elapsed": elapsed,
            "symbols": symbols,
            "files": files,
            "calls": calls,
            "raw": stats,
        }
    except Exception as e:
        print(f"  stats 失败: {e}")
        result["stats"] = {"error": str(e)[:300]}

    # 5. 核心查询性能测试
    print(f"[5/6] 核心查询性能测试...")
    queries = {}

    # 5a. search（模糊搜索）
    search_terms = {
        "admin": "Admin",
        "android": "Activity",
        "ios_muzoplayer": "ViewController",
        "firmware": "main",
    }
    term = search_terms.get(repo_name, "main")
    results = []
    try:
        results, elapsed = timed(db.search_symbols, term, limit=50)
        print(f"  search '{term}': {elapsed:.3f}s, {len(results)} 结果")
        queries["search"] = {"term": term, "elapsed": elapsed, "result_count": len(results)}
    except Exception as e:
        print(f"  search 失败: {e}")
        queries["search"] = {"error": str(e)[:300]}

    # 5b. get_callers（谁调用某符号）
    # 取 search 结果中的第一个符号作为查询目标
    first_symbol = ""
    if results:
        first_symbol = results[0].get("qualified_name", "") or results[0].get("name", "")
    if first_symbol:
        try:
            callers, elapsed = timed(db.get_callers, first_symbol)
            print(f"  get_callers '{first_symbol[:40]}': {elapsed:.3f}s, {len(callers)} 调用者")
            queries["get_callers"] = {
                "target": first_symbol[:80],
                "elapsed": elapsed,
                "result_count": len(callers),
            }
        except Exception as e:
            print(f"  get_callers 失败: {e}")
            queries["get_callers"] = {"error": str(e)[:300]}
    else:
        print(f"  get_callers 跳过（无可用符号）")

    # 5c. get_callees（某符号调用谁）
    if first_symbol:
        try:
            callees, elapsed = timed(db.get_callees, first_symbol)
            print(f"  get_callees '{first_symbol[:40]}': {elapsed:.3f}s, {len(callees)} 被调用者")
            queries["get_callees"] = {
                "target": first_symbol[:80],
                "elapsed": elapsed,
                "result_count": len(callees),
            }
        except Exception as e:
            print(f"  get_callees 失败: {e}")
            queries["get_callees"] = {"error": str(e)[:300]}
    else:
        print(f"  get_callees 跳过（无可用符号）")

    # 5d. get_topological_order（拓扑排序，测试全图遍历性能）
    try:
        topo, elapsed = timed(db.get_topological_order, limit=5000)
        print(f"  topo: {elapsed:.3f}s, {len(topo)} 节点")
        queries["topo"] = {"elapsed": elapsed, "count": len(topo)}
    except Exception as e:
        print(f"  topo 失败: {e}")
        queries["topo"] = {"error": str(e)[:300]}

    result["queries"] = queries

    # 6. clone detect（on-demand，不影响 refresh 性能；默认跳过，用 --clone 显式开启）
    if skip_clone:
        print(f"[6/6] clone detect（跳过，使用 --clone 开启）")
        queries["clone_detect"] = {"skipped": True}
    else:
        print(f"[6/6] clone detect（克隆检测）...")
        try:
            clones, elapsed = timed(db.detect_clones, min_lines=5, similarity_threshold=0.8)
            total_pairs = clones.get("total_pairs", 0)
            scanned = clones.get("scanned_symbols", 0)
            print(f"  clone detect: {elapsed:.3f}s, {total_pairs} 对, 扫描 {scanned} 符号")
            queries["clone_detect"] = {
                "elapsed": elapsed,
                "total_pairs": total_pairs,
                "scanned_symbols": scanned,
            }
        except Exception as e:
            print(f"  clone detect 失败: {e}")
            queries["clone_detect"] = {"error": str(e)[:300]}

    db.close()
    return result


def main():
    parser = argparse.ArgumentParser(description="Call Warden 性能测试脚本")
    parser.add_argument(
        "--repo",
        choices=list(REPOS.keys()),
        help="指定测试的仓库",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="依次测试全部仓库（从小到大）",
    )
    parser.add_argument(
        "--skip-refresh",
        action="store_true",
        help="跳过 refresh-all（使用已刷新的数据）",
    )
    parser.add_argument(
        "--clone",
        action="store_true",
        help="执行 clone detect（默认跳过，不污染 refresh 性能报告）",
    )
    parser.add_argument(
        "--output",
        default="tests/_perf_results.json",
        help="结果输出 JSON 文件路径",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="用本次测试的阶段耗时更新 perf 基线文件（tests/_perf_baseline.json）",
    )
    args = parser.parse_args()

    if not args.repo and not args.all:
        parser.error("必须指定 --repo 或 --all")

    repos_to_test = list(REPOS.keys()) if args.all else [args.repo]

    all_results = []
    for repo_name in repos_to_test:
        try:
            result = test_repo(repo_name, skip_refresh=args.skip_refresh, skip_clone=not args.clone)
            all_results.append(result)
        except Exception as e:
            print(f"\n[ERROR] 测试 {repo_name} 时异常: {e}")
            import traceback
            traceback.print_exc()
            all_results.append({"repo": repo_name, "error": str(e), "traceback": traceback.format_exc()})

    # 输出汇总报告
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2, default=str)

    print(f"\n{'='*60}")
    print(f"性能测试汇总报告（{len(all_results)} 个仓库）")
    print(f"{'='*60}")
    print(f"{'仓库':<16} {'refresh(s)':<12} {'符号数':<12} {'DB(MB)':<10} {'search(s)':<10}")
    print("-" * 60)
    for r in all_results:
        repo = r.get("repo", "?")
        refresh = r.get("refresh", {})
        refresh_sec = refresh.get("elapsed_sec", 0)
        stats = r.get("stats", {})
        symbols = stats.get("symbols", 0)
        db_mb = refresh.get("db_size_after_mb", 0)
        search_q = r.get("queries", {}).get("search", {})
        search_sec = search_q.get("elapsed", 0) if isinstance(search_q, dict) else 0
        print(f"{repo:<16} {refresh_sec:<12.1f} {symbols:<12} {db_mb:<10.2f} {search_sec:<10.3f}")

    print(f"\n详细结果已保存到: {output_path.absolute()}")

    # P13: 用本次测试结果更新基线文件（供后续测试做回归对比）
    if args.update_baseline:
        _update_perf_baseline(all_results)


if __name__ == "__main__":
    main()
