//! Build-time hard gate for Role Prompt Compiler v1 (frozen spec §7.4, §11.1).
//!
//! Frozen authority: docs/design/cw-role-prompt-compiler-v1-frozen-spec.md
//! SHA-256 95298729F3357CDBE76D8F8E91F12067B54D2661D6E80ABFF561A2E2A8C86CB7.
//!
//! Reads `resources/role_prompts/v1/` through the sole validator core
//! (`build_support/role_prompt_validator.rs`):
//! - manifest absent (pre-RP-02) → emits `ROLE_PROMPTS_MANIFEST_PRESENT=false`;
//! - manifest present but invalid → panics; `cargo check/build/test` fail closed;
//! - manifest valid → emits `OUT_DIR/role_prompts_generated.rs` with the
//!   compile-time hash inventory (§11.1 items 9/10).
//!
//! No bypass flag exists; drafts must live outside the scan root.

#[path = "build_support/role_prompt_validator.rs"]
mod role_prompt_validator;

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let assets_root = manifest_dir.join(role_prompt_validator::ASSETS_SUBDIR);
    let manifest_path = assets_root.join(role_prompt_validator::MANIFEST_FILE_NAME);

    // Rebuild only when the gate inputs change (keep incremental builds sane).
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support/role_prompt_validator.rs");
    if manifest_path.exists() {
        println!("cargo:rerun-if-changed={}", role_prompt_validator::ASSETS_SUBDIR);
    }

    let validation = match role_prompt_validator::validate_assets_tree(&assets_root) {
        Ok(v) => v,
        Err(issues) => {
            // Fail closed: every issue is printed; the build aborts.
            eprintln!();
            eprintln!("============================================================");
            eprintln!("role prompt build gate FAILED ({} issue[s])", issues.len());
            for (i, issue) in issues.iter().enumerate() {
                eprintln!("  [{:>2}] {}", i + 1, issue);
            }
            eprintln!("production prompt assets are invalid; fix or remove them.");
            eprintln!("============================================================");
            eprintln!();
            panic!("role prompt build gate: invalid production assets");
        }
    };

    let mut out = String::new();
    out.push_str("// @generated by build.rs from resources/role_prompts/v1 — do not edit.\n");
    out.push_str("// Frozen spec: docs/design/cw-role-prompt-compiler-v1-frozen-spec.md (§11.1).\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_MANIFEST_PRESENT: bool = {};\n\n",
        validation.manifest_present
    ).as_str());
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_MANIFEST_SHA256: &str = {:?};\n\n",
        validation.manifest_sha256
    ).as_str());
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_COMPILER_POLICY_SHA256: Option<&str> = {:?};\n\n",
        validation.compiler_policy_sha256
    ).as_str());
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_TEMPLATE_IDS: &[&str] = &[{}];\n\n",
        validation
            .templates
            .iter()
            .map(|t| format!("{:?}", t.template_id))
            .collect::<Vec<_>>()
            .join(", ")
    ).as_str());
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_TEMPLATE_PATHS: &[&str] = &[{}];\n\n",
        validation
            .templates
            .iter()
            .map(|t| format!("{:?}", t.path))
            .collect::<Vec<_>>()
            .join(", ")
    ).as_str());
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(format!(
        "pub const ROLE_PROMPTS_TEMPLATE_SHA256: &[&str] = &[{}];\n",
        validation
            .templates
            .iter()
            .map(|t| format!("{:?}", t.content_sha256))
            .collect::<Vec<_>>()
            .join(", ")
    ).as_str());

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("role_prompts_generated.rs");
    fs::write(&dest, out).expect("write role_prompts_generated.rs");
}
